### ISSUE TITLE
Help is not themed when GuiComponents are open (Menu/Options dialogs)

### ISSUE THREAD

**Issue by hex007** [RetroPie/EmulationStation#144]
Is there a way to implement this? Can someone point me in the right direction. I implemented in GuiMenu but that only works for the said dialog.

**Comment by Supernature2k** [comment]
Hi hex007

I'm trying to do the same and my guess is it should go in GuiComponent so that all menus are themed.

```
HelpStyle GuiComponent::getHelpStyle()
{
	//return HelpStyle();
	HelpStyle style;
	style.applyTheme(getTheme(), "system");
	return style;
}
```

Problem is I don't know how to retrieve the theme from here

**Comment by hex007** [comment]
@Supernature2k  I have reached to the same conclusion. I have a way to get theme in es-app module but GuiComponent is present in es-core and I dont have a way to get theme at that level.

**Comment by Supernature2k** [comment]
I may have find something but it would require to change getHelpStyle() to getHelpStyle(const std::shared_ptr<ThemeData>& theme) in several places and then something like

```
HelpStyle ViewController::getHelpStyle()
{
	if(!mCurrentView)
		return GuiComponent::getHelpStyle(mState.getSystem()->getTheme());

	return mCurrentView->getHelpStyle(mState.getSystem()->getTheme());
}

what do you think?

**Comment by Supernature2k** [comment]
I tried several ideas with no success :/

**Comment by hex007** [comment]
Fixed in commits

https://github.com/hex007/EmulationStation/commit/20ea9fd2c2d890b747678b18352f1d1b326982c0
https://github.com/hex007/EmulationStation/commit/ce3917b7720254d1308c8bc8db68c650be65db30

**Comment by pjft** [comment]
Unless you're planning on submitting a PR to the main branch, I'm not sure I'd close this issue here? It's still an issue for the main branch. 

Thanks for looking into this, though, and I do hope you manage to send things over!

**Comment by hex007** [comment]
@pjft Can you check if this is correct.

**Comment by pjft** [comment]
I shall do it in the coming days, certainly! It's a bit late here, but
thank you for going through that :)


- Paulo Tavares

**Comment by Supernature2k** [comment]
tested, working well

Do you think we could also use
```mSystem->getTheme(), "system"```
in GuiMenu?

**Comment by hex007** [comment]
@Supernature2k There is no mSystem there. Hence borrowing it from ViewController

**Comment by Supernature2k** [comment]
Hi @hex007 
I made more tests and it looks like ```ViewController::get()->reloadAll();``` makes ES crash (when changing themeset and exiting menu).

Also there is a flaw in this concept. When entering menu, there is a dim applied on background. If helpsystem has a dark font, it becomes unreadable. To mitigate this, we would need a new view tag like <view name="menu"> but of course, easier said than done.

**Comment by hex007** [comment]
@Supernature2k  I was unable to crash it. Can you elaborate how you got it to

**Comment by Supernature2k** [comment]
Menu/UI Settings/Themeset, changing the theme, back, crash.

It may be due to some submenus I added, need more tests.

**Comment by hex007** [comment]
Ok do a clean build from by branch. I am sure it is on your side as I am unable to crash it. If your build is not clean then do not report it as crashing.

**Comment by Supernature2k** [comment]
Sorry for polluting this issue. I know where the problem comes from but don't know why. May I open an issue on your repo?

**Comment by hex007** [comment]
Send link to your repo. I will look over
